spring:
  datasource:
    url: jdbc:mysql://8.142.109.15:3306/javaee?characterEncoding=utf-8
    username: root
    password: 123456
  redis:
    password: 123456
    host: 127.0.0.1
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8081